export const items = [
  { id: 1, img: "/image/icon/javascript.svg", name: "JavaScript" },
  { id: 2, img: "/image/icon/react.svg", name: "React" },
  { id: 3, img: "/image/icon/typescript.svg", name: "TypeScript" },
  { id: 4, img: "/image/icon/redux-fill.svg", name: "Redux" },
  { id: 5, img: "/image/icon/html.svg", name: "HTML" },
  { id: 6, img: "/image/icon/css.svg", name: "CSS" },
  { id: 7, img: "/image/icon/sass.svg", name: "Sass" },
  { id: 8, img: "/image/icon/git-lab-line.svg", name: "Git" },
  { id: 9, img: "/image/icon/github.svg", name: "GitHub" },
  { id: 10, img: "/image/icon/figma.svg", name: "Figma" },
  { id: 11, img: "/image/icon/reacthooks.svg", name: "React Hooks" },
  { id: 12, img: "/image/icon/axios.svg", name: "Axios" },
  { id: 13, img: "/image/icon/ESLint.svg", name: "ESLint" },
  { id: 14, img: "/image/icon/jira.svg", name: "Jira" },
  { id: 15, img: "/image/icon/JSON.svg", name: "JSON" },
  { id: 16, img: "/image/icon/rest-api.svg", name: "REST API" },
  { id: 17, img: "/image/icon/scss.svg", name: "Scss" },
  { id: 18, img: "/image/icon/vite.svg", name: "Vite" },
  { id: 19, img: "/image/icon/html5-line.svg", name: "HTML5" },
];
